{% set name = "ukpopulation" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 303f3fc66a4493eeb252c51a9a377a86df49065e1ca2345be4fb3be09e1a0859

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python>=3.6
    - pip
  run:
    - python
    - setuptools
    - numpy
    - pandas
    - requests
    - openpyxl
    - beautifulsoup4
    - lxml
    - pyexcel
    - pyexcel-xls
    - pyexcel-xlsx
    - ukcensusapi

test:
  imports:
    - ukpopulation.myedata
    - ukpopulation.snppdata
    - ukpopulation.nppdata
    - ukpopulation.snhpdata

about:
  home: https://github.com/nismod/ukpopulation
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Download, cache, collate, filter and extrapolate UK Population estimates and projections
  dev_url: https://github.com/nismod/ukpopulation

extra:
  recipe-maintainers:
    - virgesmith
    - tomalrussell
