{% set name = "ukpopulation" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5f412182b4b2f0db899c7b6551d9d5b01f825dfbd25ea02f85488efbe4526f3

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy
    - pandas
    - requests
    - openpyxl
    - beautifulsoup4
    - lxml
    - pyexcel
    - pyexcel-xls
    - pyexcel-xlsx
    - ukcensusapi

test:
  imports:
    - ukpopulation.myedata
    - ukpopulation.snppdata
    - ukpopulation.nppdata
    - ukpopulation.snhpdata

about:
  home: https://github.com/nismod/ukpopulation
  license: MIT
  license_family: MIT
  license_file: LICENCE
  summary: Download, cache, collate, filter and extrapolate UK Population estimates and projections
  dev_url: https://github.com/nismod/ukpopulation

extra:
  recipe-maintainers:
    - virgesmith
    - tomalrussell
