travis:
  secure:
    BINSTAR_TOKEN: YCFHvMy+4bPNuzOXH6gnjr6QIi8gEjOfM5aunPy+Ea90q1p8/cAaz+6OIJOZnYFWilasFRT+ELDirM6UV8L4Dl4syw9DQBfqm8+bdtbv9GY5FfSuRGJYrMuV1ObnpRvdjzE34pvI2xGO4SuGlMEuVp7c7gxBmnSuLq1MSGLcJ0sfjL650QoIJEToWDgOZ8SMTn2rd3QrJDV/WOA9k6qTlfg672q+1KcNwF5sJc9QXxjgxG0sJ9iP8OYayhfnl2euZcRW9N356xj4YuimvDGrbGjmrI0HuIBCj4W7UyzUcf5wa/yvxBgyULtKD2lwSgrWlYmmsVJh8o8UVQTatLV9mLdwG2CvVZ71zLpnaL7MT60r4IT4/W7cTpXClg0DSxbnd82RRQGn1rI+saIBBFo/AX0oPx94P5/mSOtz/kLARt5PR6SOsUNuwOkhJT/S4pw5HTlmI35dM/ctDHY3nrU4e/pzL+yq3KVnDo30gEzVhnNjQ96CyPZqjYzrfBEP19qcGeCNSIJRCAo543BmwblUHqAnPVegW9ABF7cA3gImJtMBXRFuytzicZS58WofgVN5ZLlidc/6kU9sIwUcy0JX+R+jJ+gwddzMDKjM9aVC2BLVllVoGPJj1UtHmgDu51W44LAGr1vfKG/4Uay0jkcc8BhfIJBlsdH5OoZCF138VDE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
