travis:
  secure:
    BINSTAR_TOKEN: NoRFi14hdTzmCP3/MU6CjtTuGJo6o+2mxun/qWIqfHa7b58x8bggKSkTMFyEGbhLZFP5y1soMjtU52nOfOK+rlsKvQdui5H7U32Lc6YkbknMSloOAq5PkcUpMRHbWwKZOQ4sH9K/rSJGGehNE1WRZ4MHrW2Nvk7gFawJkhGCMhJVjI9upIZnITjQZJ5kDwVQqI2yl7JXweYDrFomAno0hXgKNiB9sFUJDZcoT66QzZCddmhE1jd9mikuSWsxcsepDvo4lvfg/Xfh7gsA9ht3vmhiTWhF922Ksy+2yESRy/u1tk2znsNDfN0nb5hGEFFvpUNF9qgvDz8e25ZdJ3c5uzIE4jMgIaNq5IAkR+RVxr9VvZnz9xn4pTeCekOCjwdM35lvjFY0Q4nKw7DQXqkLkPUaU645zW2bJvKhkkVfdvDJ6riWPXJQ8M+lZOCJv4X1Pm6h8udtCk1WAkGix443edASQSke9yMJVsF+xbHvVBR/Am2eZIUflOf9ZH5Z2OKLLk3Hy5YjWKmaa1DcPRxFDuUoIoK/INBSvyLrw5Lizox0Z+zMrLV2ZunRGsOZBE0IxUV8Bg6GP1PvjtquOER/LnbxV+bfKwT5yL0dFNBMC6zS0QcS8mOb4mIubbfDEfXMfQRIjVTjkGrrAYEr93oxRenPfcxlHOtTqgpxLvV+JYs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
